# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code Cube
email: leechee89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.teslalee.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tesla_lee
github_username:  liqites

environment: prod
google_analytics: UA-83593915-2

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-awesome
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true     # You no longer need to include --livereload
reload_port: 5678

paginate: 10
paginate_path: "/blog/page:num/"

assets:
  compress:
    css: false # | true | default - development: false, production: true
    js: false # | true | default - development: false, production: true
  autowrite: true
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
