#!/bin/bash

# clean _deploy_path

deploypath="./_deploy"

start_time=`date`
echo "【`date +%T`】开始生成网站"

bundle exec jekyll build --config _config_prod.yml --destination ./_deploy

echo "【`date +%T`】生成网站成功"
echo "【`date +%T`】开始发布"

cd $deploypath
git add .
git add -u
git commit -m "Deployed at `date`"
git push origin master
echo "【`date +%T`】发布网站成功"
